base:
  project: simple-dvc-project
  random_state: 42
  target_col: quality
  test_size: 0.2

data_source:
  s3_source: https://dvc-demo-dataset.s3.us-east-1.amazonaws.com/winequality_data/winequality-red.csv?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEK3%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCmFwLXNvdXRoLTEiRzBFAiEA%2BLmjA25JE28HA1wpUazvlQCbMUfj2RZZLh4C%2BxAXkgICIG8o4Mg%2BZLNZBIXaNIiKTUCoSfOE0VtFDE1IXxeexWfMKuQCCHYQABoMMTM1ODg3OTk0MDE1Igy3w%2FNdJRjCRqU%2BL3QqwQIyZUJa9kpTC%2FFg7UBVXcp8BuijbvZQByKs3uHIeAVvD%2FERNWTW8W90SPBpucmQozjSyXUM1CbyDlJKhpDjoXT1SqEF0xlXg8z5%2FIb1XmUR3AonCUJCUyR1RQP6ZQwjI7FVsJBdg%2B%2F1quEoTnlZRlhtTtK9OYIzUSzmrpEbw6YPqnRx2tQRBw1yQCEMyeJEsV%2F9yIpc3sfpva5Ad%2Bq%2BwZXp%2BX9fZ41yk2eLSWr%2F4Bp4mnYuYEKy63Y1H6T0qRB4QFtSvcg%2BC5b6a7WXCJawGQz431ig%2BFR83oyx%2Fb8ZAbQttUvak9nH7jgHGoYtAFms%2FhTzMBbTo%2F7JeNK1b9zOOq95mVk4rZQ8HVooYwcL6Ge1uty5Q6sgmHAyBM0%2FkuOBEkV7qSSYYns1ObZbmWhnQZshQ1B4Keu0ZR9nEPURjym9CVgw%2F8aVmgY6swK5ZiE4GAC9oHnHhI3TEP2HKOL8%2Bz%2FML7pyUKWFjob1k%2FRrK8Cng6ipMgNmGPvhe%2Bjl8fBp3EaPZnOp319DposMJ%2Be%2F%2Br3XvqmzvLLdEOK%2FJMzelZyv4lrZ0uESs4bJEeHtcWFdX6PWmNq99CrH0F2TU7A3DUl3FqcBSEebdgyQLVLXKyv0GypOICtiw9QH0m2gHdu7lOvdfLqyGVaMdAaB78AXEHK6BIHXWqU9LiKwnk0pK6hyAodx3XVEQdFzAaapyCnYYdcuH%2BHq2iEIcNDC%2FvEmzD9T63tQWDWarxAeejLmn3LHFEhFNgAFI9AdbZosWTrEEzxEp4tQ2rwCrrSYeB%2F2UVirVd%2FEAjO1P1kiqvTrSek%2FTS2yz%2FnAdZgk3iQ0KUOxu6dw7EFyYi0mm18eY5l4&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20221011T123805Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIAR7I4OHSPUTCZTXEF%2F20221011%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=53cc2b9429134938e89aa9b3783c3de589636f58a887d1a419ae23fcb7413627

artifacts:
  artifacts_dir: artifacts

  raw_local_data_dir: artifacts/raw_local_data_dir
  raw_local_data: artifacts/raw_local_data_dir/data.csv

  split_data:
    processed_data_dir: artifacts/processed_data
    train_path: artifacts/processed_data/train.csv
    test_path: artifacts/processed_data/test.csv


  reports:
    reports_dir: artifacts/report
    params: artifacts/report/params.json
    scores: artifacts/report/scores.json

  model_dir: artifacts/saved_models
  model_path: artifacts/saved_models/model.joblib

estimators:
  ElasticNet:
    params:
      alpha: 0.9
      l1_ratio: 0.4
      